# ---
# include:
#   - "**/*.rb"
# exclude:
#   - spec/**/*
#   - test/**/*
#   - vendor/**/*
#   - ".bundle/**/*"
# require: []
# domains: []
# reporters:
#   - rubocop
#   - require_not_found
#   - typecheck:strict
# formatter:
#   rubocop:
#     cops: safe
#     except: []
#     only: []
#     extra_args: []
# require_paths: []
# plugins: []
# max_files: 5000

#Solargarph config for rails
---
include:
  - "app/**/*.rb"
  - "config/**/*.rb"
  - "lib/**/*.rb"
exclude:
  - spec/**/*
  - vendor/**/*
  - ".bundle/**/*"
require:
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activesupport
domains: []
reporters:
  - rubocop
  - require_not_found
  - typecheck
  - update_errors
formatter:
  rubocop:
    cops: safe
    except: []
    only: []
    extra_args: []
require_paths: []
plugins:
  - solargraph-rails
max_files: 5000
